# Generated by Django 3.2.8 on 2021-10-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acwebui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formalDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('sim_threshold', models.FloatField()),
                ('seg_threshold', models.FloatField()),
                ('sim_materials', models.FloatField()),
                ('diff_fourier', models.BooleanField()),
                ('diff_dynamic', models.BooleanField()),
                ('strict_equality', models.BooleanField()),
                ('Alignement', models.BooleanField()),
                ('diff_concordance', models.BooleanField()),
                ('rule_1', models.BooleanField()),
                ('rule_2', models.BooleanField()),
                ('rule_3', models.BooleanField()),
                ('rule_4', models.BooleanField()),
                ('rule_5', models.BooleanField()),
                ('transitory_frame', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DF',
        ),
    ]
