# Generated by Django 3.2.8 on 2021-10-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acwebui', '0002_auto_20211014_1839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='parameters',
            new_name='parameter',
        ),
    ]
