# Generated by Django 3.2.8 on 2021-10-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acwebui', '0003_rename_parameters_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='Alignement',
            new_name='alignement',
        ),
        migrations.AlterField(
            model_name='formaldiagram',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='file',
            field=models.FileField(upload_to='audio'),
        ),
    ]
