# Generated by Django 3.2.8 on 2021-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acwebui', '0004_auto_20211015_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='cqt',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='fft',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='mfcc',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
