# Generated by Django 3.2.8 on 2021-10-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acwebui', '0005_auto_20211015_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formaldiagram',
            name='image',
        ),
    ]
