# Generated by Django 3.2.8 on 2021-10-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acwebui', '0006_remove_formaldiagram_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='alignement',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='cqt',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='diff_concordance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='diff_dynamic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='diff_fourier',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='fft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='mfcc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='rule_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='rule_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='rule_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='rule_4',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='rule_5',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='seg_threshold',
            field=models.FloatField(default=160),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='sim_materials',
            field=models.FloatField(default=0.94),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='sim_threshold',
            field=models.FloatField(default=0.975),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='strict_equality',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='transitory_frame',
            field=models.BooleanField(default=False),
        ),
    ]
