# Generated by Django 3.2.8 on 2021-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acwebui', '0019_auto_20211022_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Jean', max_length=50)),
                ('surname', models.CharField(default='Dupont', max_length=50)),
                ('email', models.EmailField(default='jean.dupont@mail.fr', max_length=254)),
                ('musicologist', models.BooleanField(default=False)),
                ('musician', models.BooleanField(default=False)),
                ('comment', models.TextField(default='Laissez un commentaire...')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
