# Generated by Django 3.2.8 on 2021-11-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acwebui', '0020_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='alignement',
        ),
    ]
