# Generated by Django 3.2.8 on 2021-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acwebui', '0021_remove_parameter_alignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='alignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='euclid_distance',
            field=models.BooleanField(default=False),
        ),
    ]
