# Generated by Django 3.2.8 on 2021-11-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acwebui', '0022_auto_20211106_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='seg_threshold',
            field=models.FloatField(default=150),
        ),
    ]
